version: '3'

services:
  ledmatrix-server:
    build: .
    environment:
      PORT: 8080
      NODE_ENV: development
      MATRIX_URL: debug
    restart: always
    volumes:
      - ../packages/server:/app

  ledmatrix-app:
    build: .
    environment:
      PORT: 8080
      NODE_ENV: development
      NUXT_HOST: 0.0.0.0
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../packages/app:/app
