version: '3'

services:
  ledmatrix:
    build: .
    environment:
      PORT: 8080
      NODE_ENV: development
      MATRIX_URL: debug
    restart: always
    volumes:
      - ../packages/server:/app

  ledmatrix-spa:
    build: .
    environment:
      PORT: 8080
      NODE_ENV: development
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../packages/app:/app
